...

diff --git a/src/14/Dockerfile b/src/14/Dockerfile
--- a/src/14/Dockerfile
+++ b/src/14/Dockerfile
@@ -1,29 +1,54 @@
-FROM node:14
+FROM node:14-alpine
 
-RUN apt-get update \
- && apt-get install -y \
-    apt-transport-https \
-    build-essential \
-    ca-certificates \
-    curl \
-    dirmngr \
+# Configure the system
+RUN apk add --no-cache \
+    bash \
     gcc \
     git \
-    gnupg \
+    g++ \
     make \
-    patch \
+    shadow \
     ruby \
-    ruby-dev \
+    openssh-client \
+    python \
+    py-pip \
     python3 \
-    wget \
-    xz-utils
+ && python3 -m ensurepip
 
-# Install SASS
-RUN gem install sass --no-user-install
+# Install gosu
+ENV GOSU_VERSION 1.11
+RUN set -eux; \
+	\
+	apk add --no-cache --virtual .gosu-deps \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+# for flaky keyservers, consider https://github.com/tianon/pgp-happy-eyeballs, ala https://github.com/docker-library/php/pull/666
+	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	command -v gpgconf && gpgconf --kill all || :; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+# clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
 
-# Copy over the entry point so we can modify the user
-COPY usr/bin/entry-point /usr/bin/entry-point
-RUN chmod +x /usr/bin/entry-point
+# Add the entry point
+ADD usr/local/bin/docker-image-entrypoint.sh /usr/local/bin/docker-image-entrypoint
+
+# Add Bower to the image
+RUN npm install -g bower
 
 # The directory to work from
 WORKDIR /data
@@ -31,16 +56,8 @@ WORKDIR /data
 # The volume that can be mounted
 VOLUME /data
 
-# Install gosu
-RUN set -eux; \
-	apt-get update; \
-	apt-get install -y gosu; \
-	rm -rf /var/lib/apt/lists/*; \
-    # verify that the binary works
-	gosu nobody true
+# Run all commands via the entry point
+ENTRYPOINT ["/usr/local/bin/docker-image-entrypoint"]
 
-# Execute the entry point
-ENTRYPOINT ["/usr/bin/entry-point"]
-
-# The default command to execute
+# The default command to run
 CMD ["node"]
